[tool.ruff]
select = ["E", "F", "B"]
ignore = ["E501"]
line-length = 100
target-version = "py312"

[tool.ruff.format]
line-length = 100

[tool.pytest.ini_options]
testpaths = ["tests"]
norecursedirs = ["pyscf"]
